#!/usr/bin/env node

const { readFileSync, writeFileSync, statSync } = require('fs')
const { join } = require('path')

const genScript = (title, data) => `
set term qt 0 font "Verdana,7" size 1280,640
unset key
set autoscale x noextend
set xtics format "%Y" nomirror
set ytics format "$%.0f" nomirror
set xdata time
set grid 
iso_fmt = "%Y-%m-%d"
set timefmt iso_fmt
mid(s, e) = s + (e - s) / 2
threemo=8035200
sixmo=16070400
ninemo=24105600
rank(d) = d < threemo ? 1 : d < sixmo ? 2 : d < ninemo ? 3 : 4
set title "${title}" font ",10"
plot "-" using (mid(timecolumn(2, iso_fmt), timecolumn(3, iso_fmt))):1:2:3:(rank(timecolumn(3, iso_fmt) - timecolumn(2, iso_fmt))) with xerrorbars linecolor variable pointtype 0
${data}`.trimStart()

const ONE_WEEK = 7 * 24 * 60 * 60 * 1000

const stale = file => {
    try {
        const { mtime } = statSync(file)
        const weekAgo = new Date(Number(mtime) - ONE_WEEK)
        return mtime < weekAgo
    } catch (_) {}
    return true
}

const fetchEdgar = (url, options) => fetch(url, {
    ...options,
    headers: {
        Accept: 'application/json',
        'Accept-Encoding': 'gzip, deflate',
        'User-Agent': process.env.EDGAR_UA,
        ...options
    }
}).then(async resp => {
    const body = await resp.text()

    if (!resp.ok) {
        throw new Error(`request failed\nGET ${url}\n${resp.status} ${resp.statusText}\n${body}`)
    }

    return body
})

const fetchFacts = async cik => {
    console.error('facts stale, fetching...')
    return fetchEdgar(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`)
}

const getOrCache = async (file, fn) => {
    if (!stale(file)) return readFileSync(file, 'utf8')
    const result = await fn()
    writeFileSync(file, result, 'utf8')
    return result
}

const factspath = path => join(process.env.HOME, '.facts', path)

const getFacts = async (cik) => 
    JSON.parse(await getOrCache(factspath(`${cik}.json`), () => fetchFacts(cik)))

const usage = (status = 0) => {
    console.error('usage: plotfacts <cikOrName> <concept>')
    process.exit(status)
}

const threshold = diff => {
    if (diff < 93) return 1
    if (diff < 186) return 2
    if (diff < 279) return 3
    return 4
}

const diffDays = (y, x) => {
    if (!x) return 0
    const time = y.getTime() - x.getTime()
    return time / (24 * 60 * 60 * 1000)
}

const allowedUnits = ["USD", "USD/shares"]

const formatAsData = (concept, rank) => {
    const unit = allowedUnits.find(u => concept?.units?.[u])

    const facts = concept?.units?.[unit]?.reduce((facts, fact) => {
        const { end, filed, fp } = fact

        const e = new Date(end)

        if (!fact.start) {
            const t = new Date(e)
            t.setUTCDate(1)
            const m = fp === 'FY' || !fp ? 11 : 2
            t.setUTCMonth(t.getUTCMonth() - m)
            fact.start = t.toISOString().split('T')[0]
        }

        const s = new Date(fact.start)
        const k = `${end}${fact.start}`
        const v = facts[k]

        fact.rank = threshold(diffDays(e, s))

        if (!v || v.filed < filed) facts[k] = fact

        return facts
    }, {})

    const sortedFacts = Object.values(facts).filter(f => {
        if (!rank) return true
        return f.rank == rank
    }).sort((f1, f2) => {
        const t = f1.rank - f2.rank
        if (t !== 0) return t
        return new Date(f1.end) - new Date(f2.end)
    })

    return sortedFacts.map(({ start, end, val }) => `${val} ${start} ${end}`)?.join('\n')
}

const fetchCompanyTickers = () => {
    console.error('company tickers stale, fetching...')
    return fetchEdgar('https://www.sec.gov/files/company_tickers.json')
}

const getCompanyTickers = async () => 
    JSON.parse(await getOrCache(factspath(`company_tickers.json`), fetchCompanyTickers))

const findCik = async cikOrNamePattern => {
    if (/^\d+$/.test(cikOrNamePattern)) return cikOrNamePattern

    const companies = Object.values(await getCompanyTickers())
    const cik = companies.find(({ ticker }) => ticker === cikOrNamePattern)?.cik_str?.toString()

    if (cik) return cik

    const nameRe = new RegExp(cikOrNamePattern, 'i')
    const filtered = companies.filter(({ title }) => nameRe.test(title))

    if (filtered.length === 1) return filtered[0].cik_str?.toString()
    else if (filtered.length > 1) {
        filtered.forEach(company => console.log(company.title))
        return process.exit(0)
    } else {
        console.error('error: no companies found')
        return usage(1)
    }
}

const main = async () => {
    const [,, cikOrNamePattern, conceptPattern, rank] = process.argv
    const cik = await findCik(cikOrNamePattern)

    if (!cik) {
        console.error('error: missing cik or name pattern')
        usage(1)
    }

    if (!conceptPattern) {
        console.error('error: missing concept pattern')
        usage(1)
    }

    const conceptRe = new RegExp(conceptPattern, 'i')

    const { entityName, facts } = await getFacts(cik.padStart(10, '0'))

    const concepts = facts?.["us-gaap"]
    const selected = Object.keys(concepts).sort().filter(c => {
        if (!allowedUnits.some(u => concepts[c].units[u])) return false
        return conceptRe.test(c)
    })

    if (selected.length > 1) {
        selected.forEach(s => console.log(s))
        return 
    }

    if (!selected.length) {
        console.error('error: no concepts found')
        usage(1)
    }

    const concept = concepts[selected[0]]
    const title = `${entityName} - ${concept.label}`
    const data = formatAsData(concept, rank)

    console.log(genScript(title, data))
}

main()